# Generated by Django 3.0.7 on 2021-09-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201128_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='temp_token',
            field=models.TextField(default=''),
        ),
    ]
